---
- name: Add Zabbix repo CentOS 7
  become: yes
  yum: name={{ zabbix_package_centos7 }} state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Add Zabbix repo CentOS 6
  become: yes
  yum: name={{ zabbix_package_centos6 }} state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: Install Zabbix-Agent Ubuntu 18
  become: yes
  apt: deb={{ zabbix_package_ubuntu18 }} 
  when: when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
  
- name: Install Zabbix-Agent Ubuntu 16
  become: yes
  apt: deb={{ zabbix_package_ubuntu16 }} 
  when: when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"
  
- name: Config zabbix-agent 
  become: yes
  template:
     src="zabbix_agentd.conf.j2"
     dest="/etc/zabbix/zabbix_agentd.conf"
     mode=0644
     owner=root
     group=root
  notify: restart zabbix_agent